# Site settings
title: Goh Jian Wei Nigel
name: Goh Jian Wei Nigel

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/thenigelgoh
 - title: LinkedIn
   url: https://www.linkedin.com/in/gohjianweinigel/

#Any buzzword skills you want to include
skills:
 - Python
 - Matlab
 - Solidworks
 - C
 - Machine learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list

#Work experience is required
roles:
 - title: Section Commander 
   start: 2014
   end: 2016
   employer: Singapore Armed Forces
   description: Trained as a Military Policeman specialist. Served in the detention platoon and helped in control of operations in the cell block and basic regimentation and development of competencies in subordinates.
 - title: Business Development Intern
   start: June 2018
   end: August 2018
   employer: MegaX
   description: A breakout project under iFashion Group, MEGAX (MGX) are spendable blockchain-based tokens on a wide and growing retail network of more than 40,000 brands.<br/>The tokens are centered around a millennial movement, created by profitable, revenue generating retail companies - such as the guys who brought you Artbox Singapore. <br/>MGX successfully completed its ICO in November 2017, raising S$3.3mil.<br/>To promote the use of cryptocurrency amongst millenials in retail, MGX will create and partner with epic retail events that exclusively accept MGX tokens as payment.<br/>Expect unique artisanal markets to be organised worldwide, attracting millions of consumers, leading to accelerated awareness and adoption of MGX.
 - title: Project Engineering Intern
   start: May 2019 
   end: August 2019
   employer: Kruger Engineering Pte Ltd
   description: Assisted project engineers in the following areas: <br/>Fan Selection based on Customer Requirements, <br/>Static Pressure Calculation for ducting systems, <br/>Noise Analysis for Fans Selected, <br/>Preparation of Quotations in response to Customer Enquiries

#Education is required
education:
 - level: Bachelor of Aerospace Engineering
   date: 2020
   subject: Aerospace Engineering with second major in Business (Banking and Finance)
   school: Nanyang Technological University

#This section is optional (as is the image link below)


#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute


#List of interesting Github repo/projects to include - optional



#Stackoverflow flair is optional

intro: |
  Aerospace Engineering Undergraduate interested in seeking new opportunities in the Aerospace Engineering Industry; Willing to take on new challenges and step outside my comfort zone. 

Looking for job opportunities in Aerospace-related companies from August 2020 onwards.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
